version: "2"
plugins:
  csslint:
    enabled: true
  scss-lint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
  eslint:
    enabled: true
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
exclude_patterns:
  - "public/"
  - "tests/"
  - "coverage/"
  - "node_modules/"
