language: node_js
node_js:
  - "node"
  - "lts/*"
cache: yarn
script: yarn test --coverage
before_script:
  - npm install codeclimate-test-reporter -g
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info